import { sql, initializeDatabase } from "@/lib/db";

const loanProducts = [
  // Personal Loans (12 products)
  {
    name: "Quick Personal Loan",
    bank: "HDFC Bank",
    type: "personal",
    rate_apr: 10.5,
    min_income: 300000,
    min_credit_score: 750,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 2,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary:
      "Instant personal loan with minimal documentation and fast approval",
    faq: JSON.stringify([
      { q: "How long does approval take?", a: "24-48 hours for most cases" },
      {
        q: "Can I prepay without penalty?",
        a: "Yes, prepayment is allowed without charges",
      },
    ]),
  },
  {
    name: "Salary Plus Personal Loan",
    bank: "ICICI Bank",
    type: "personal",
    rate_apr: 11.25,
    min_income: 250000,
    min_credit_score: 700,
    tenure_min_months: 12,
    tenure_max_months: 72,
    processing_fee_pct: 2.5,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary:
      "Flexible personal loan with competitive rates for salaried professionals",
  },
  {
    name: "Flexi Personal Loan",
    bank: "SBI",
    type: "personal",
    rate_apr: 9.75,
    min_income: 400000,
    min_credit_score: 720,
    tenure_min_months: 6,
    tenure_max_months: 84,
    processing_fee_pct: 1.5,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Low-interest personal loan from India's largest bank",
  },
  {
    name: "Express Cash Loan",
    bank: "Axis Bank",
    type: "personal",
    rate_apr: 12.5,
    min_income: 200000,
    min_credit_score: 680,
    tenure_min_months: 12,
    tenure_max_months: 48,
    processing_fee_pct: 3,
    prepayment_allowed: false,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Quick cash loan with minimal eligibility requirements",
  },
  {
    name: "Prime Personal Loan",
    bank: "Kotak Mahindra Bank",
    type: "personal",
    rate_apr: 10.99,
    min_income: 350000,
    min_credit_score: 740,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 2,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Premium personal loan with exclusive benefits for high earners",
  },
  {
    name: "Instant Approval Loan",
    bank: "IndusInd Bank",
    type: "personal",
    rate_apr: 11.75,
    min_income: 240000,
    min_credit_score: 690,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 2.5,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Digital personal loan with instant approval and disbursal",
  },
  {
    name: "Smart Personal Loan",
    bank: "Yes Bank",
    type: "personal",
    rate_apr: 13.25,
    min_income: 180000,
    min_credit_score: 650,
    tenure_min_months: 12,
    tenure_max_months: 36,
    processing_fee_pct: 3.5,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Accessible personal loan for mid-income professionals",
  },
  {
    name: "Premium Cash Loan",
    bank: "Standard Chartered",
    type: "personal",
    rate_apr: 10.25,
    min_income: 500000,
    min_credit_score: 760,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 1.5,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Exclusive personal loan for high net worth individuals",
  },
  {
    name: "Everyday Loan",
    bank: "RBL Bank",
    type: "personal",
    rate_apr: 14.5,
    min_income: 150000,
    min_credit_score: 640,
    tenure_min_months: 6,
    tenure_max_months: 48,
    processing_fee_pct: 4,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Flexible personal loan with easy approval criteria",
  },
  {
    name: "Digital Personal Loan",
    bank: "IDFC First Bank",
    type: "personal",
    rate_apr: 11.5,
    min_income: 280000,
    min_credit_score: 710,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 2,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "100% digital personal loan with paperless approval",
  },
  {
    name: "Festive Personal Loan",
    bank: "Punjab National Bank",
    type: "personal",
    rate_apr: 12.99,
    min_income: 220000,
    min_credit_score: 670,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 2.5,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Special rate personal loan for all your festive needs",
  },
  {
    name: "Flex Pay Loan",
    bank: "Bank of Baroda",
    type: "personal",
    rate_apr: 13.75,
    min_income: 190000,
    min_credit_score: 660,
    tenure_min_months: 12,
    tenure_max_months: 48,
    processing_fee_pct: 3,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Flexible repayment options with competitive interest rates",
  },

  // Home Loans (10 products)
  {
    name: "Home Loan Advantage",
    bank: "HDFC Bank",
    type: "home",
    rate_apr: 8.5,
    min_income: 600000,
    min_credit_score: 750,
    tenure_min_months: 60,
    tenure_max_months: 360,
    processing_fee_pct: 0.5,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary:
      "Affordable home loan with attractive interest rates for first-time buyers",
  },
  {
    name: "Smart Home Loan",
    bank: "SBI",
    type: "home",
    rate_apr: 8.35,
    min_income: 500000,
    min_credit_score: 730,
    tenure_min_months: 60,
    tenure_max_months: 360,
    processing_fee_pct: 0.35,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "India's most trusted home loan with lowest processing fees",
  },
  {
    name: "Dream Home Loan",
    bank: "ICICI Bank",
    type: "home",
    rate_apr: 8.65,
    min_income: 550000,
    min_credit_score: 740,
    tenure_min_months: 60,
    tenure_max_months: 360,
    processing_fee_pct: 0.5,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Fast processing home loan with digital documentation",
  },
  {
    name: "Express Home Loan",
    bank: "Axis Bank",
    type: "home",
    rate_apr: 8.75,
    min_income: 520000,
    min_credit_score: 720,
    tenure_min_months: 60,
    tenure_max_months: 300,
    processing_fee_pct: 0.6,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Quick approval home loan with minimal documentation",
  },
  {
    name: "Premium Home Loan",
    bank: "Kotak Mahindra Bank",
    type: "home",
    rate_apr: 8.45,
    min_income: 700000,
    min_credit_score: 760,
    tenure_min_months: 60,
    tenure_max_months: 360,
    processing_fee_pct: 0.4,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Exclusive home loan for premium customers with best rates",
  },
  {
    name: "First Home Loan",
    bank: "LIC Housing Finance",
    type: "home",
    rate_apr: 8.55,
    min_income: 480000,
    min_credit_score: 710,
    tenure_min_months: 60,
    tenure_max_months: 300,
    processing_fee_pct: 0.5,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Affordable home loan for first-time home buyers",
  },
  {
    name: "Women's Home Loan",
    bank: "SBI",
    type: "home",
    rate_apr: 8.25,
    min_income: 450000,
    min_credit_score: 720,
    tenure_min_months: 60,
    tenure_max_months: 360,
    processing_fee_pct: 0.25,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Special rates for women borrowers with reduced processing fees",
  },
  {
    name: "Green Home Loan",
    bank: "HDFC Bank",
    type: "home",
    rate_apr: 8.4,
    min_income: 550000,
    min_credit_score: 740,
    tenure_min_months: 60,
    tenure_max_months: 360,
    processing_fee_pct: 0.3,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Eco-friendly home loan with special rates for green buildings",
  },
  {
    name: "Balance Transfer Home Loan",
    bank: "ICICI Bank",
    type: "home",
    rate_apr: 8.5,
    min_income: 600000,
    min_credit_score: 750,
    tenure_min_months: 60,
    tenure_max_months: 360,
    processing_fee_pct: 0.5,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Transfer your existing home loan and save on interest",
  },
  {
    name: "NRI Home Loan",
    bank: "Axis Bank",
    type: "home",
    rate_apr: 9.25,
    min_income: 800000,
    min_credit_score: 760,
    tenure_min_months: 60,
    tenure_max_months: 300,
    processing_fee_pct: 0.75,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Home loan specially designed for Non-Resident Indians",
  },

  // Education Loans (8 products)
  {
    name: "Student Education Loan",
    bank: "SBI",
    type: "education",
    rate_apr: 7.5,
    min_income: 300000,
    min_credit_score: 680,
    tenure_min_months: 60,
    tenure_max_months: 180,
    processing_fee_pct: 0,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary:
      "Comprehensive education loan covering tuition and living expenses",
  },
  {
    name: "Vidya Lakshmi Scheme",
    bank: "Bank of Baroda",
    type: "education",
    rate_apr: 8.15,
    min_income: 250000,
    min_credit_score: 650,
    tenure_min_months: 60,
    tenure_max_months: 180,
    processing_fee_pct: 0,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Government-backed education loan with subsidized interest rates",
  },
  {
    name: "Global Education Loan",
    bank: "HDFC Credila",
    type: "education",
    rate_apr: 9.5,
    min_income: 400000,
    min_credit_score: 720,
    tenure_min_months: 84,
    tenure_max_months: 180,
    processing_fee_pct: 1,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Specialized loan for studying at top universities abroad",
  },
  {
    name: "Scholar Loan",
    bank: "ICICI Bank",
    type: "education",
    rate_apr: 8.75,
    min_income: 320000,
    min_credit_score: 700,
    tenure_min_months: 60,
    tenure_max_months: 180,
    processing_fee_pct: 0.5,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary:
      "Flexible education loan for undergraduate and postgraduate studies",
  },
  {
    name: "Career Education Loan",
    bank: "Axis Bank",
    type: "education",
    rate_apr: 9.25,
    min_income: 280000,
    min_credit_score: 690,
    tenure_min_months: 60,
    tenure_max_months: 156,
    processing_fee_pct: 1,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Education loan for professional courses and skill development",
  },
  {
    name: "Study Abroad Loan",
    bank: "Punjab National Bank",
    type: "education",
    rate_apr: 8.9,
    min_income: 350000,
    min_credit_score: 710,
    tenure_min_months: 72,
    tenure_max_months: 180,
    processing_fee_pct: 0.5,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary:
      "Comprehensive loan covering education expenses for overseas studies",
  },
  {
    name: "Skill Development Loan",
    bank: "Canara Bank",
    type: "education",
    rate_apr: 8.35,
    min_income: 200000,
    min_credit_score: 660,
    tenure_min_months: 36,
    tenure_max_months: 84,
    processing_fee_pct: 0,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Loan for vocational training and skill enhancement programs",
  },
  {
    name: "IIM MBA Loan",
    bank: "Auxilo Finserve",
    type: "education",
    rate_apr: 10.5,
    min_income: 500000,
    min_credit_score: 750,
    tenure_min_months: 60,
    tenure_max_months: 144,
    processing_fee_pct: 2,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "standard",
    summary: "Premium education loan for top business schools in India",
  },

  // Vehicle Loans (6 products)
  {
    name: "New Car Loan",
    bank: "HDFC Bank",
    type: "vehicle",
    rate_apr: 8.75,
    min_income: 350000,
    min_credit_score: 720,
    tenure_min_months: 12,
    tenure_max_months: 84,
    processing_fee_pct: 1,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Attractive rates for purchasing brand new cars",
  },
  {
    name: "Used Car Loan",
    bank: "ICICI Bank",
    type: "vehicle",
    rate_apr: 9.95,
    min_income: 280000,
    min_credit_score: 680,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 1.5,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Finance your pre-owned car purchase with flexible terms",
  },
  {
    name: "Two Wheeler Loan",
    bank: "Bajaj Finserv",
    type: "vehicle",
    rate_apr: 11.5,
    min_income: 180000,
    min_credit_score: 650,
    tenure_min_months: 12,
    tenure_max_months: 48,
    processing_fee_pct: 2,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Quick approval loan for bikes and scooters",
  },
  {
    name: "Electric Vehicle Loan",
    bank: "SBI",
    type: "vehicle",
    rate_apr: 8.25,
    min_income: 400000,
    min_credit_score: 730,
    tenure_min_months: 12,
    tenure_max_months: 84,
    processing_fee_pct: 0.5,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Special subsidy rates for electric and hybrid vehicles",
  },
  {
    name: "Commercial Vehicle Loan",
    bank: "Axis Bank",
    type: "vehicle",
    rate_apr: 10.25,
    min_income: 450000,
    min_credit_score: 710,
    tenure_min_months: 24,
    tenure_max_months: 60,
    processing_fee_pct: 2,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Finance trucks, taxis, and other commercial vehicles",
  },
  {
    name: "Luxury Car Loan",
    bank: "Kotak Mahindra Bank",
    type: "vehicle",
    rate_apr: 9.5,
    min_income: 800000,
    min_credit_score: 760,
    tenure_min_months: 12,
    tenure_max_months: 84,
    processing_fee_pct: 1.5,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Exclusive financing for premium and luxury car segments",
  },

  // Credit Line (2 products)
  {
    name: "FlexiCredit Line",
    bank: "HDFC Bank",
    type: "credit_line",
    rate_apr: 15.5,
    min_income: 400000,
    min_credit_score: 750,
    tenure_min_months: 0,
    tenure_max_months: 0,
    processing_fee_pct: 1,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Revolving credit facility with instant access to funds",
  },
  {
    name: "Smart Credit Line",
    bank: "ICICI Bank",
    type: "credit_line",
    rate_apr: 16.25,
    min_income: 350000,
    min_credit_score: 720,
    tenure_min_months: 0,
    tenure_max_months: 0,
    processing_fee_pct: 1.5,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Pre-approved credit line for emergency financial needs",
  },

  // Debt Consolidation (2 products)
  {
    name: "Debt Consolidation Loan",
    bank: "SBI",
    type: "debt_consolidation",
    rate_apr: 11.5,
    min_income: 400000,
    min_credit_score: 720,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 2,
    prepayment_allowed: true,
    disbursal_speed: "standard",
    docs_level: "standard",
    summary: "Consolidate all your loans into one with lower EMI",
  },
  {
    name: "Balance Transfer Plus",
    bank: "Axis Bank",
    type: "debt_consolidation",
    rate_apr: 12.25,
    min_income: 350000,
    min_credit_score: 700,
    tenure_min_months: 12,
    tenure_max_months: 60,
    processing_fee_pct: 2.5,
    prepayment_allowed: true,
    disbursal_speed: "fast",
    docs_level: "low",
    summary: "Transfer high-interest loans and save on monthly payments",
  },
];

async function seed() {
  try {
    console.log("🌱 Starting database seed...");

    // Initialize database
    await initializeDatabase();

    // Clear existing products
    await sql`DELETE FROM products`;
    console.log("🗑️  Cleared existing products");

    // Insert all loan products
    for (const product of loanProducts) {
      await sql`
        INSERT INTO products (
          name, bank, type, rate_apr, min_income, min_credit_score,
          tenure_min_months, tenure_max_months, processing_fee_pct,
          prepayment_allowed, disbursal_speed, docs_level, summary, faq
        ) VALUES (
          ${product.name},
          ${product.bank},
          ${product.type},
          ${product.rate_apr},
          ${product.min_income},
          ${product.min_credit_score},
          ${product.tenure_min_months},
          ${product.tenure_max_months},
          ${product.processing_fee_pct},
          ${product.prepayment_allowed},
          ${product.disbursal_speed},
          ${product.docs_level},
          ${product.summary},
          ${product.faq || "[]"}
        )
      `;
    }

    console.log(`✅ Successfully seeded ${loanProducts.length} loan products`);

    // Display summary
    const counts = await sql`
      SELECT type, COUNT(*) as count 
      FROM products 
      GROUP BY type
      ORDER BY type
    `;

    console.log("\n📊 Product Summary:");
    counts.forEach((row: any) => {
      console.log(`   ${row.type}: ${row.count} products`);
    });

    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seed();
